# Generated by Django 3.0.5 on 2020-05-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=512)),
                ('deploy_key_path', models.CharField(default='', max_length=128, null='')),
                ('deploy_key_priv', models.CharField(default='', max_length=2048, null='')),
                ('deploy_key_pub', models.CharField(default='', max_length=2048, null='')),
                ('details_json', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Skillet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('skillet_json', models.TextField(default='', max_length=2048)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc.RepositoryDetails')),
            ],
        ),
    ]
